name: Register
version: '1.0-SNAPSHOT'
main: org.plugin.register.Register
api-version: '1.16'
commands:
  reg:
    description: "Reg you on server"
    usage: "/reg [пароль] [повтор пароля]"
    aliases:
    permission: register.command.reg
    permission-message: "You do not have permission"
  log:
    description: "Log in your account"
    usage: "/log [пароль]"
    aliases:
    permission: register.command.reg
    permission-message: "You do not have permission"
permissions:
  register.command.reg:
    default: true

